In [23]:
# Install NumPy
## pip install numpy 

In [1]:
import numpy as np #Import Numpy after downloading as np (where np is an alias)

In [25]:
a = np.array([1, 2, 3])  # Create a 1D array
print(a)
print(a[0]) #Print first element of array

[1 2 3]
1


In [26]:
b = np.array([[1,2,3],[4,5,6]])
print(b)
print(b[0,0])#Print first element (0 th row, 0th col) of 2D array
print(b[1,1])#Print element at (1,1) of 2D array

[[1 2 3]
 [4 5 6]]
1
5


# Array Attributes

In [27]:
a.ndim  # Number of dimensions of array a


1

In [28]:
b.ndim  # Number of dimensions of array b

2

## Shape of an array

In [29]:
a.shape  # Shape of array a

(3,)