In [2]:
# Install NumPy
## pip install numpy 

# What is NumPy?

- NumPy is the fundamental package for scientific computing in Python.
- It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

In [2]:
import numpy as np #Import Numpy after downloading as np (where np is an alias)

In [3]:
a = np.array([1, 2, 3])  # Create a 1D array
print(a)
print(a[0]) #Print first element of array

[1 2 3]
1


In [4]:
b = np.array([[1,2,3],[4,5,6]])
print(b)
print(b[0,0])#Print first element (0 th row, 0th col) of 2D array
print(b[1,1])#Print element at (1,1) of 2D array

[[1 2 3]
 [4 5 6]]
1
5


In [24]:
comp = np.array([[1,2],[3,4.6+ 25j]],dtype = complex)

In [25]:
print(comp)

[[1.  +0.j 2.  +0.j]
 [3.  +0.j 4.6+25.j]]


#### NumPy arrays have a fixed size at creation, unlike Python lists (which are dynamic).
#### Changing the size of an "ndarray"will create a new array and delete the original one.

# Array Attributes

In [5]:
a.ndim  # Number of dimensions of array a


1

In [6]:
b.ndim  # Number of dimensions of array b

2

## Shape of an array

In [7]:
a.shape  # Shape of array a

(3,)

In [8]:
b.shape

(2, 3)

## Size of Array
total number of elements of the array. This is equal to the product of the elements of shape.

In [9]:
a.size

3

In [10]:
b.size

6

## DType
an object describing the type of the elements in the array. 

In [11]:
a.dtype

dtype('int64')

In [12]:
b.dtype

dtype('int64')

In [17]:
c = np.array(['hi', 1, 2, 3])

In [18]:
c.dtype

dtype('<U21')

## Itemsize
the size in bytes of each element of the array. 


In [20]:
a.itemsize 

8

In [21]:
c.itemsize

84

---

## Basic Operations

In [28]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
print(a)
print(b)

[20 30 40 50]
[0 1 2 3]


In [36]:
#Addition 
a + b

#subtraction
a - b

#product
a * b

#divide
a / (b + 1)

array([20.        , 15.        , 13.33333333, 12.5       ])

In [37]:
#Power
a ** b

array([     1,     30,   1600, 125000])

In [38]:
a < 35


array([ True,  True, False, False])

In [39]:
A = np.array([[1, 1], [5, 1]])
B = np.array([[2, 1], [3, 4]])

In [42]:
A * B #elementwise product

array([[ 2,  1],
       [15,  4]])

In [43]:
A @ B #matrix product

array([[ 5,  5],
       [13,  9]])