# Creating a Basic Array

In [2]:
import numpy as np

## 1D Array

In [2]:
a = np.array([1, 2, 3])  # Create a 1D array
print(a)
print(a[0]) #Print first element of array

[1 2 3]
1


In [5]:
np.zeros(2)

array([0., 0.])

In [6]:
b = np.zeros(3)
print(b)

[0. 0. 0.]


In [11]:
np.empty(3)

array([0., 0., 0.])

In [5]:
np.ones(3)

array([1., 1., 1.])

## 2D Array

In [4]:
b = np.array([[1,2,3],[4,5,6]])
print(b)
print(b[0,0])#Print first element (0 th row, 0th col) of 2D array
print(b[1,1])#Print element at (1,1) of 2D array

[[1 2 3]
 [4 5 6]]
1
5


In [7]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
z = np.zeros((3,4))
print(z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [7]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

## np.arange()

In [15]:
c = np.arange(4)
print(c)

[0 1 2 3]


In [ ]:
d = np.arange(2,9,2)  #Start at 2, end before 9, step by 2
print(d)

[2 4 6 8]


In [17]:
e = np.arange(5,16,3)  #Start at 5, end before 16, step by 3
print(e)

[ 5  8 11 14]


## np.linspace()

In [ ]:
np.linspace(0, 10, 5) #Generate 5 values spaced linearly between 0 and 10

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
np.linspace(0,10,6) #Generate 6 values spaced linearly between 0 and 10

array([ 0.,  2.,  4.,  6.,  8., 10.])

## Specifying your data type

In [23]:
x = np.ones(2, dtype=int)
print(x)

[1 1]


In [27]:
x = np.array([1,2.2,2], dtype=int)
print(x)

[1 2 2]
