# Sorting array

In [2]:
import numpy as np

In [5]:
arr = np.array([1, 2, 23, 15, 5])
print(arr)

[ 1  2 23 15  5]


In [6]:
np.sort(arr)

array([ 1,  2,  5, 15, 23])

In [ ]:
np.argsort(arr) #Get the indices that would sort the array

array([0, 1, 4, 3, 2])

# Concatenation

In [9]:
a = np.array([1, 2, 3]) 
b = np.array([4, 5, 6])
np.concatenate((a, b))  #Concatenate arrays a and b

array([1, 2, 3, 4, 5, 6])

# Shape & Size

In [ ]:
ar = np.array([3, 1, 2])
ar.ndim  #Get the number of dimensions of the array


(3,)

In [ ]:
ar.size #Get the total number of elements in the array

(3,)

In [13]:
ar.shape #Get the shape of the array

(3,)

# arr.reshape()

In [23]:
a = np.arange(6)  #Create an array with values from 1 to 10 with a step of 2
print(a)

[0 1 2 3 4 5]


In [24]:
b = a.reshape(3, 2) 
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [26]:
np.reshape(a, shape=(1,6), order='c')

array([[0, 1, 2, 3, 4, 5]])