# Selecting Values

In [2]:
import numpy as np

In [3]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(a[a<5]) #print values less than 5

[1 2 3 4]


In [4]:
five_up = (a>5)
print(a[five_up]) #print values greater than 5  

[6 7 8]


In [5]:
print(a[a%2 == 0]) #print even values only

[2 4 6 8]


In [6]:
five_up = (a > 5) | (a == 5)
print(five_up) #boolean array where values greater than or equal to 5 are True

[[False False False False]
 [ True  True  True  True]]


## np.nonzero() to print the indices of elements that are

In [7]:
b = np.nonzero(a<5)
print(b)

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))


## Slicing

In [18]:
data = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
data[0,1]

np.int64(2)

In [11]:
data[0:2]

array([[1, 2],
       [3, 4]])

In [12]:
data[1:]

array([[3, 4],
       [5, 6],
       [7, 8]])

In [13]:
data[:3]

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
data[-1]

array([7, 8])

In [15]:
data[-2:]

array([[5, 6],
       [7, 8]])

In [19]:
c = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
c.shape

(3, 3)

In [ ]:
c[1,...] # second row same as c[1,:,:] or c[1]

array([40, 50, 60])

In [21]:
c[...,2] # third column same as c[:,2]  

array([30, 60, 90])

## Iteration

In [26]:
c = np.array([[1,2,3], [4,5,6], [7,8,9]])
for row in c:   
    print(row)
    
for column in c.T:
    print(column)

[1 2 3]
[4 5 6]
[7 8 9]
[1 4 7]
[2 5 8]
[3 6 9]


In [ ]:
for item in c.flat:  #c.flat is a 1-D iterator over the array
    print(item)

1
2
3
4
5
6
7
8
9
