# Selecting Values

In [1]:
import numpy as np

In [3]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(a[a<5]) #print values less than 5

[1 2 3 4]


In [4]:
five_up = (a>5)
print(a[five_up]) #print values greater than 5  

[6 7 8]


In [5]:
print(a[a%2 == 0]) #print even values only

[2 4 6 8]


In [6]:
five_up = (a > 5) | (a == 5)
print(five_up) #boolean array where values greater than or equal to 5 are True

[[False False False False]
 [ True  True  True  True]]


## np.nonzero() to print the indices of elements that are

In [7]:
b = np.nonzero(a<5)
print(b)

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))


## Slicing