# Change Shape of an Array

In [1]:
import numpy as np

In [6]:
a = np.floor(10*np.random.random((3,4)))
print(a)
a.shape

[[0. 8. 4. 0.]
 [0. 9. 9. 5.]
 [2. 5. 7. 5.]]


(3, 4)

In [7]:
a.ravel() # returns the flattened array

array([0., 8., 4., 0., 0., 9., 9., 5., 2., 5., 7., 5.])

In [ ]:
a.reshape(4,3) # returns the reshaped array
#NOTE: Ensure elements number be same by multiplying the value you give in reshape

array([[0., 8., 4.],
       [0., 0., 9.],
       [9., 5., 2.],
       [5., 7., 5.]])

In [10]:
a.T # returns the transposed array

array([[0., 0., 2.],
       [8., 9., 5.],
       [4., 9., 7.],
       [0., 5., 5.]])

In [12]:
a.resize(2,6) # changes the shape of the array inplace
print(a)

[[0. 8. 4. 0. 0. 9.]
 [9. 5. 2. 5. 7. 5.]]


## Stack Together different arrays

In [14]:
a = np.array([10, 20, 30, 40, 50])
b = np.array([1, 2, 3, 4, 5])

In [15]:
np.vstack((a,b))  # vertical stack

array([[10, 20, 30, 40, 50],
       [ 1,  2,  3,  4,  5]])

In [16]:
np.hstack((a,b))  # horizontal stack

array([10, 20, 30, 40, 50,  1,  2,  3,  4,  5])

In [17]:
np.column_stack((a,b))  # column stack

array([[10,  1],
       [20,  2],
       [30,  3],
       [40,  4],
       [50,  5]])

In [18]:
np.concatenate((a,b))  # concatenate

array([10, 20, 30, 40, 50,  1,  2,  3,  4,  5])

## Splitting

In [22]:
arr = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])

In [ ]:
np.hsplit(arr, 3)  # horizontal split into 3 parts

[array([[1, 2],
        [7, 8]]),
 array([[ 3,  4],
        [ 9, 10]]),
 array([[ 5,  6],
        [11, 12]])]

In [28]:
np.vsplit(arr,1)  # vertical split into 1 part

[array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])]

In [32]:
np.vsplit(arr,2)  # vertical split into 2 parts

[array([[1, 2, 3, 4, 5, 6]]), array([[ 7,  8,  9, 10, 11, 12]])]